import { type Signal } from '@angular/core';
import { type Attrs } from './attrs';

/**
 * OTel-shaped correlation ids, generated by the facade and shared across every
 * sink for a span, so a multi-sink span correlates to one trace.
 */
export interface SpanContext {
  readonly traceId: string; // 16-byte hex
  readonly spanId: string; // 8-byte hex
  readonly parentSpanId?: string;
}

/** A sink's per-span object. `end` receives the facade-stamped epoch ms so
 *  buffered spans replay with their true end time, not the flush time. */
export interface SinkSpan {
  setAttrs(attrs: Attrs): void;
  setError(err: unknown): void;
  end(endMs?: number): void;
}

// Capability interfaces — an adapter implements only the subset it supports.
export interface SpanSink {
  /** `startMs` is the facade-stamped epoch ms of the span's start — honor it if
   *  the backend models time, so readiness-buffered spans keep real timestamps. */
  startSpan(name: string, ctx: SpanContext, attrs?: Attrs, startMs?: number): SinkSpan;
}
export interface EventSink {
  capture(name: string, attrs?: Attrs): void;
}
export interface ErrorSink {
  recordError(err: unknown, attrs?: Attrs): void;
}

/** OTel instrument families. The adapter maps these onto its metric instruments. */
export type MetricKind = 'counter' | 'gauge' | 'histogram';
export interface MetricSink {
  record(name: string, value: number, attrs?: Attrs, kind?: MetricKind): void;
}

/** OTel severity tiers (mapped to SeverityNumber by the adapter). */
export type LogSeverity =
  | 'trace'
  | 'debug'
  | 'info'
  | 'warn'
  | 'error'
  | 'fatal';

export interface LogRecord {
  readonly severity: LogSeverity;
  readonly body: string;
  readonly attrs?: Attrs;
  /** Epoch ms for the log event; the adapter stamps emit time when omitted. */
  readonly timestamp?: number;
}

/**
 * Structured log lines (OTLP logs → Loki/etc.). Distinct from `ErrorSink`, which
 * is exception capture (Sentry-style). A backend may implement both.
 */
export interface LogSink {
  emitLog(record: LogRecord): void;
}

export type Sink = Partial<
  SpanSink & EventSink & ErrorSink & MetricSink & LogSink
> & {
  readonly name: string;
  /**
   * Signal-native: a sink can be async-initialised. While *initially* `false`,
   * the facade buffers telemetry and flushes it in order when this flips `true`.
   * If the flip takes longer than `readyTimeoutMs` (default ~5s) the buffer is
   * dropped so a broken sink can't leak memory; live delivery still resumes when
   * the sink eventually becomes ready. Readiness is a one-way latch: flipping
   * back to `false` later does not re-buffer.
   */
  readonly ready: Signal<boolean>;
  /**
   * Optional teardown, invoked when the providing injector is destroyed. Flush
   * exporters, clear intervals, remove listeners here.
   */
  dispose?(): void;
};

/**
 * A sink, or a **factory that builds one**. `provideTelemetry` invokes factories
 * inside its provider factory — i.e. in an injection context — so an adapter that
 * needs DI (e.g. `inject(TelemetryHandles)` to publish vendor handles, or any
 * other service) just returns `() => sink` and calls `inject()` in its body.
 * Falsy results (and falsy entries) are dropped, so adapters can return
 * `null`/`undefined` for invalid config.
 */
export type SinkInput =
  | Sink
  | null
  | undefined
  | (() => Sink | null | undefined);

/**
 * Opaque to consumers: you pass it as a parent and let `telemetry.span` manage it.
 * Read its raw context only via `readSpan()` for advanced cases.
 */
export interface SpanHandle {
  readonly ctx: SpanContext;
  setAttrs(attrs: Attrs): void;
  setError(err: unknown): void;
  end(): void;
}
