export {
  compose,
  composition,
  fromMetadata,
  injectField,
  injectFieldRef,
  raw,
  type Composition,
  type CompositionOptions,
  type CompositionRule,
  type FieldProjection,
  type FieldProjector,
  type FieldRef,
  type Projectable,
  type Projected,
  type RawProjection,
} from './compose';
